// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUGIr7eAdvBIht7v9PuW-Q6Z_Xv-tDRqQ',
    appId: '1:687695411049:web:162dba888f029a4cb7aff8',
    messagingSenderId: '687695411049',
    projectId: 'talkready-a8496',
    authDomain: 'talkready-a8496.firebaseapp.com',
    storageBucket: 'talkready-a8496.firebasestorage.app',
    measurementId: 'G-HM621P1FWW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBqLsT9-MyLmY_RXj83kXOswmWbYlL3og',
    appId: '1:687695411049:android:0f724b3f43b7cd4eb7aff8',
    messagingSenderId: '687695411049',
    projectId: 'talkready-a8496',
    storageBucket: 'talkready-a8496.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfgUaXXrpkTeLJNhtJRZT3XNBpz81dBYU',
    appId: '1:687695411049:ios:f5bcd14f3755a6b4b7aff8',
    messagingSenderId: '687695411049',
    projectId: 'talkready-a8496',
    storageBucket: 'talkready-a8496.firebasestorage.app',
    androidClientId: '687695411049-1pmbkvckh08206bloi0uf2tt9hql0227.apps.googleusercontent.com',
    iosClientId: '687695411049-qdmdb0nce6d2tbv6l021m0nt25s1p8ld.apps.googleusercontent.com',
    iosBundleId: 'com.example.talkreadyMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfgUaXXrpkTeLJNhtJRZT3XNBpz81dBYU',
    appId: '1:687695411049:ios:f5bcd14f3755a6b4b7aff8',
    messagingSenderId: '687695411049',
    projectId: 'talkready-a8496',
    storageBucket: 'talkready-a8496.firebasestorage.app',
    androidClientId: '687695411049-1pmbkvckh08206bloi0uf2tt9hql0227.apps.googleusercontent.com',
    iosClientId: '687695411049-qdmdb0nce6d2tbv6l021m0nt25s1p8ld.apps.googleusercontent.com',
    iosBundleId: 'com.example.talkreadyMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUGIr7eAdvBIht7v9PuW-Q6Z_Xv-tDRqQ',
    appId: '1:687695411049:web:e799a732895f8963b7aff8',
    messagingSenderId: '687695411049',
    projectId: 'talkready-a8496',
    authDomain: 'talkready-a8496.firebaseapp.com',
    storageBucket: 'talkready-a8496.firebasestorage.app',
    measurementId: 'G-VRC5WSJZ10',
  );

}